apiVersion: v1
kind: Service
metadata:
  name: namemetadata
  namespace: defaultnamespace
  labels:
    app: applabel
spec:
  ports:
  - name: tcp1111
    port: 1111
    protocol: TCP
    targetPort: 1111
  selector:
    app: appselector
  sessionAffinity: None
  type: ClusterIP